## title: "run_analysis_markdown"
### author: "barb dornseif - saoirsegirl"
date: "October 25, 2014"  output: html_document

----
## Sourcing, Importing and Loading the needed files
Data for this program is sourced and described at the following websites.  
**Information about the experiment** design and data collection assumptions are at:
http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones

**Files are located at:** https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip

The initial dataset is a .zip files which includes four .txt files and two folders. They are:  
**folder: test/**     
 *   subject_test.txt  
 *   X_test.txt  
 *   y_test  
     +   folder: Inertial Signals/ (this is raw data we will not be using)    
     
**folder: train/**  
 *  subject_train.txt  
 *  X_train.txt  
 *  y_train.txt  
     +  folder: Inertial Signals/ (this is raw data we will not be using)    

* README.txt  
* features.txt (a list of all features in X_test/train.txt)  
* features_info. (a code book descsribing the data)  
* activity_labels.txt -- the six descriptions for the numeric factors in y_test/train.txt  

Further descriptions of the starting dataset and the methods of its compilation as described in the "Features_info.txt" file are attached below.   
  
Manipulations and Reorganizations  
-------------
1. The program will take the above data sets, first column merge the 3 files in each folder (x , y and subject_info) and then row merge the "test"" and "train" sets into one large data.frame.  No data elements are transformed or altered in these steps. Column names for the 561 "X" data columns are attached prior to the merge.  
2. With theses column names in place, the program will make its first content adjustment - selecting only those columns that calculate a "mean" or "standard deviation".  The assumption of this program is that the meanFreq() is calculated using the mean() function prior to our handling with Freq being added to indicate a variable and not statistical difference in the calculation performed. Thus they fall into this catagory. This first step of tidying is created as a data.frame "tidyData1".  
3. "tidyData1" and the "activities" lookup are merged to add the descriptive names associated with each observation.  A new data.frame is created "tidyData2".   
4. column names are added to the "Y" and "subject" data columns -  "activity" and "Subject".  Note "activity" id the numeric factor variable and "Activity" is the full named factor variable inherited in the prior step, but reinforced in this renaming.  
5. aggregate the metrics by the factor variables Subject and Activity to create a new data.frame "submitData".  Write to .txt file "submitData.txt" for upload into Coursera.  

Feature Selection  
=================

The features selected for this database come from the accelerometer and gyroscope 3-axial raw signals tAcc-XYZ and tGyro-XYZ. These time domain signals (prefix 't' to denote time) were captured at a constant rate of 50 Hz. Then they were filtered using a median filter and a 3rd order low pass Butterworth filter with a corner frequency of 20 Hz to remove noise. Similarly, the acceleration signal was then separated into body and gravity acceleration signals (tBodyAcc-XYZ and tGravityAcc-XYZ) using another low pass Butterworth filter with a corner frequency of 0.3 Hz. 

Subsequently, the body linear acceleration and angular velocity were derived in time to obtain Jerk signals (tBodyAccJerk-XYZ and tBodyGyroJerk-XYZ). Also the magnitude of these three-dimensional signals were calculated using the Euclidean norm (tBodyAccMag, tGravityAccMag, tBodyAccJerkMag, tBodyGyroMag, tBodyGyroJerkMag). 

Finally a Fast Fourier Transform (FFT) was applied to some of these signals producing fBodyAcc-XYZ, fBodyAccJerk-XYZ, fBodyGyro-XYZ, fBodyAccJerkMag, fBodyGyroMag, fBodyGyroJerkMag. (Note the 'f' to indicate frequency domain signals). 

These signals were used to estimate variables of the feature vector for each pattern:  
'-XYZ' is used to denote 3-axial signals in the X, Y and Z directions.

tBodyAcc-XYZ  
tGravityAcc-XYZ  
tBodyAccJerk-XYZ  
tBodyGyro-XYZ  
tBodyGyroJerk-XYZ  
tBodyAccMag  
tGravityAccMag  
tBodyAccJerkMag  
tBodyGyroMag  
tBodyGyroJerkMag  
fBodyAcc-XYZ  
fBodyAccJerk-XYZ  
fBodyGyro-XYZ  
fBodyAccMag  
fBodyAccJerkMag  
fBodyGyroMag  
fBodyGyroJerkMag  

The set of variables that were estimated from these signals are: 

mean(): Mean value  
std(): Standard deviation  
mad(): Median absolute deviation   
max(): Largest value in array  
min(): Smallest value in array  
sma(): Signal magnitude area  
energy(): Energy measure. Sum of the squares divided by the number of values.   
iqr(): Interquartile range   
entropy(): Signal entropy  
arCoeff(): Autorregresion coefficients with Burg order equal to 4  
correlation(): correlation coefficient between two signals  
maxInds(): index of the frequency component with largest magnitude  
meanFreq(): Weighted average of the frequency components to obtain a mean frequency  
skewness(): skewness of the frequency domain signal   
kurtosis(): kurtosis of the frequency domain signal   
bandsEnergy(): Energy of a frequency interval within the 64 bins of the FFT of each window.  
angle(): Angle between to vectors.  

Additional vectors obtained by averaging the signals in a signal window sample. These are used on the angle() variable:

gravityMean  
tBodyAccMean  
tBodyAccJerkMean  
tBodyGyroMean  
tBodyGyroJerkMean  

The complete list of variables of each feature vector is available in 'features.txt'  